### PR TITLE
Correct semantics in and add additional semantics to the afterword

### PR DESCRIPTION
**Pull request by MagisterAdamus**
This adds semantics to some previously "unsemanticated" Roman numerals and personal name abbreviations/initials, as well as correcting the `datetime` semantics for a year that was incorrectly listed as `1893` instead of `1926`.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! You can put all of this stuff together into one PR if it's easier for you.

**Comment by MagisterAdamus** [comment]
I thought that things that form separate units of work, e.g., correcting typos vs. adding semantics, are supposed to be separate, right? But before, the reason that I had separated the corrections to the bodymatter and to the afterword was because I was quite tired after going through all of the bodymatter and needed a bit of a break.

**Comment by acabal** [comment]
Correct, but you can have as many commits as you want in one PR. I don't care about PRs, I care about a clean commit history.

**Comment by MagisterAdamus** [comment]
Oh! Now I understand. Thanks for the clarification! I was conflating commits and PRs for some reason, even though I understand that they are separate concepts.

**Pull request merged**
